### ISSUE TITLE
Dynamic Camera Movement and Controls

### ISSUE THREAD

**Issue by fallinbryan** [professorsquish/PSquish_Prod#2]
Add a pill player, implement the player controls with camera tag along

**Comment by fallinbryan** [comment]
Add a pill player,  implement the player controls with camera tag along

**Comment by Leolab216** [comment]
Still need to get jumping smooth, otherwise working

**Comment by fallinbryan** [comment]
Don't worry about syncing the jump to the animation.  Once you have good air time and height for the jump, I will adjust the animation frames to sync with the jump.

**Comment by Leolab216** [comment]
We're good in that case.
