### ISSUE TITLE
Start Menu

### ISSUE THREAD

**Issue by fallinbryan** [professorsquish/PSquish_Prod#3]
Menu Pops when Game starts,  has button to play, a difficulty slider, and a question button.  +any good ideas for a start menu you may have

-- functionality to UI elements will be added later

**Comment by yeikel** [comment]
How many difficulties are we having? EASY - MEDIUM - HARD? 

What's the question button for? Get help?

**Comment by fallinbryan** [comment]
Easy - Medium - Hard
Yes, for get help.

The help "page/popup" will be kid simple.  The controls, and basic concept of the game

For button controls, create an empty object called Game Controller,  then create a GameController.cs script that has the function in it the buttons will execute

**Comment by fallinbryan** [comment]
For the vertical slice,  the difficulty setting won't actually do anything.  Just have them there for the next phase.

**Comment by fallinbryan** [comment]
For this issue,  the only functionality we need is for the start menu to show when the game starts,  and start playing the game when the play game button is clicked.

If you look in the old code, under the game controller,  the code to pause the game is in that script.  Basically set time to 0.  We can start the game with the time set to zero in the new game controller, then when click play, set the start menu gameObject.active = false and set the time back to 1

**Comment by yeikel** [comment]
Waiting for feedback , otherwise please close it
