### ISSUE TITLE
player should only use weapon if the weapon has been built

### ISSUE THREAD

**Issue by fallinbryan** [professorsquish/PSquish_Prod#55]
right now from the start, player can use any weapon.  turn that off and make it so player can only use a weapon that has been built

**Comment by yeikel** [comment]
It is very unclear how weapons are built to begin with. I'll say let's create another issue to clarify that

**Comment by fallinbryan** [comment]
collect part
hit esc
click inventory
drag part into  dark area
click upgrade
weapon built

**Comment by yeikel** [comment]
What parts build what? I think we need a guide or something like that

**Comment by fallinbryan** [comment]
acid tank -> acid gun
fuel  tank +igniter -> flame thrower
battery + tesla coil -> tesla gun

**Comment by fallinbryan** [comment]
what happened to issue to add that to the help menu?

**Comment by yeikel** [comment]
I don't believe we ever had one. We just discussed that in the call

**Comment by yeikel** [comment]
Unfortunately I can't work on the project today tho. At most tomorrow but it might be too late

**Comment by fallinbryan** [comment]
I did not reference this issue a minute ago...  wtf is going on?

**Comment by yeikel** [comment]
I did

**Comment by fallinbryan** [comment]
oh, I see what happened.  I was real confused for a second

**Comment by yeikel** [comment]
I just updated your comment

**Comment by yeikel** [comment]
![image](https://user-images.githubusercontent.com/8935151/56095991-5aac3100-5eb0-11e9-8aab-03765d0da2a0.png)

**Comment by fallinbryan** [comment]
in progress

**Comment by fallinbryan** [comment]
done
