### ISSUE TITLE
Story audio is not playing

### ISSUE THREAD

**Issue by yeikel** [professorsquish/PSquish_Prod#58]
Audio that used to play at the help menu telling the story of the game is not working 

![image](https://user-images.githubusercontent.com/8935151/56107134-8cee7a80-5f12-11e9-9f32-1c8bd43c302a.png)

**Comment by fallinbryan** [comment]
volume was initialized at zero.
added line to GameController to init volume to 0.4f
Story does not play automatically when you open help, click the speaker icon and the story will start, click it again and it will stop, 

issue resolved.
